<a href="https://colab.research.google.com/github/iamatul1214/NLP/blob/main/Make_Model_from_Transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%cd /content/drive/MyDrive/Transformer_practice

/content/drive/MyDrive/Transformer_practice


In [2]:
try:
  from transformers import pipeline
except Exception as e:
  print(e)
  print("installing...")
  !pip install datasets transformers[sentencepiece] -q
  from transformers import pipeline

No module named 'transformers'
installing...
     |████████████████████████████████| 346 kB 14.8 MB/s 
     |████████████████████████████████| 4.2 MB 73.5 MB/s 
     |████████████████████████████████| 140 kB 65.5 MB/s 
     |████████████████████████████████| 86 kB 5.9 MB/s 
     |████████████████████████████████| 212 kB 76.5 MB/s 
     |████████████████████████████████| 86 kB 6.4 MB/s 
     |████████████████████████████████| 1.1 MB 57.0 MB/s 
     |████████████████████████████████| 596 kB 67.4 MB/s 
     |████████████████████████████████| 127 kB 76.2 MB/s 
     |████████████████████████████████| 144 kB 79.6 MB/s 
     |████████████████████████████████| 94 kB 3.2 MB/s 
     |████████████████████████████████| 271 kB 80.4 MB/s 
     |████████████████████████████████| 112 kB 78.3 MB/s 
     |████████████████████████████████| 6.6 MB 58.3 MB/s 
     |████████████████████████████████| 1.2 MB 59.2 MB/s 
ERROR: pip's dependency resolver does not currently take into account all the packages that

In [3]:
classifier = pipeline("sentiment-analysis")
classifier("I love my country")

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)


Downloading:   0%|          | 0.00/629 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/255M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

[{'label': 'POSITIVE', 'score': 0.9998471736907959}]

In [4]:
from transformers import AutoTokenizer

In [5]:
ckpt = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer=AutoTokenizer.from_pretrained(ckpt)

In [6]:
inputs = "I love my country"

In [7]:
tokenizer(inputs)

{'input_ids': [101, 1045, 2293, 2026, 2406, 102], 'attention_mask': [1, 1, 1, 1, 1, 1]}

In [9]:
batch_input = ["I love my country",
               "I am Atul and I work at Mindtree"]

In [11]:
out = tokenizer(batch_input, padding=True)
out

{'input_ids': [[101, 1045, 2293, 2026, 2406, 102, 0, 0, 0, 0, 0, 0], [101, 1045, 2572, 2012, 5313, 1998, 1045, 2147, 2012, 2568, 13334, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [12]:
type(out)

transformers.tokenization_utils_base.BatchEncoding

In [13]:
out_pytorch_tensors = tokenizer(batch_input, padding=True, return_tensors="pt")
out_pytorch_tensors

{'input_ids': tensor([[  101,  1045,  2293,  2026,  2406,   102,     0,     0,     0,     0,
             0,     0],
        [  101,  1045,  2572,  2012,  5313,  1998,  1045,  2147,  2012,  2568,
         13334,   102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [14]:
out_TF_tensors = tokenizer(batch_input, padding=True, return_tensors="tf")
out_TF_tensors

{'input_ids': <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[  101,  1045,  2293,  2026,  2406,   102,     0,     0,     0,
            0,     0,     0],
       [  101,  1045,  2572,  2012,  5313,  1998,  1045,  2147,  2012,
         2568, 13334,   102]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [15]:
from transformers import AutoModel

In [16]:
model_ckpt = AutoModel.from_pretrained(ckpt)   ## creating new model from scratch with the checkpoints weights

Some weights of the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing DistilBertModel: ['classifier.weight', 'pre_classifier.weight', 'classifier.bias', 'pre_classifier.bias']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [17]:
model_ckpt

DistilBertModel(
  (embeddings): Embeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (transformer): Transformer(
    (layer): ModuleList(
      (0): TransformerBlock(
        (attention): MultiHeadSelfAttention(
          (dropout): Dropout(p=0.1, inplace=False)
          (q_lin): Linear(in_features=768, out_features=768, bias=True)
          (k_lin): Linear(in_features=768, out_features=768, bias=True)
          (v_lin): Linear(in_features=768, out_features=768, bias=True)
          (out_lin): Linear(in_features=768, out_features=768, bias=True)
        )
        (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        (ffn): FFN(
          (dropout): Dropout(p=0.1, inplace=False)
          (lin1): Linear(in_features=768, out_features=3072, bias=True)
          (lin2): Linear(i

In [18]:
logits = model_ckpt(**out_pytorch_tensors)
logits

BaseModelOutput([('last_hidden_state',
                  tensor([[[ 0.4521,  0.2584,  0.0448,  ...,  0.4836,  0.8697, -0.2664],
                           [ 0.5710,  0.4134,  0.0491,  ...,  0.5090,  0.7748, -0.2068],
                           [ 0.8872,  0.5492,  0.2826,  ...,  0.3853,  0.8563, -0.2052],
                           ...,
                           [ 0.1293,  0.1981, -0.0614,  ...,  0.5446,  0.7708, -0.1253],
                           [ 0.0972,  0.2152, -0.0695,  ...,  0.5433,  0.7558, -0.1254],
                           [ 0.2259,  0.4079, -0.0303,  ...,  0.4686,  0.7017, -0.1708]],
                  
                          [[ 0.7784,  0.3615, -0.0109,  ..., -0.1357,  1.0306, -0.3059],
                           [ 0.8477,  0.6325, -0.4751,  ..., -0.1694,  1.0763, -0.4218],
                           [ 0.2511,  0.9028,  0.5000,  ..., -0.4019,  0.5669, -0.0406],
                           ...,
                           [ 0.2644, -0.2001,  0.4922,  ...,  0.3055,  0.273

In [19]:
batch_size, sequence_len, Hidden_state= logits["last_hidden_state"].shape
batch_size, sequence_len, Hidden_state

(2, 12, 768)

In [20]:
from transformers import AutoModelForSequenceClassification
model_2 = AutoModelForSequenceClassification.from_pretrained(ckpt)
pred = model_2(**out_pytorch_tensors) 
pred

SequenceClassifierOutput([('logits', tensor([[-4.2268,  4.5594],
                                   [-1.7788,  1.7339]], grad_fn=<AddmmBackward0>))])

In [21]:
import torch
pred_prob = torch.nn.functional.softmax(pred.logits, dim=1)
print(pred_prob)

tensor([[1.5280e-04, 9.9985e-01],
        [2.8953e-02, 9.7105e-01]], grad_fn=<SoftmaxBackward0>)


In [22]:
model_2.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [23]:
torch.argmax(pred_prob, dim=-1)

tensor([1, 1])