<a href="https://colab.research.google.com/github/iamatul1214/NLP/blob/main/Tokenizer_in_transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
## changing the diretory to root
%cd /content/drive/MyDrive/Transformer_practice

/content/drive/MyDrive/Transformer_practice


In [3]:
!pwd

/content/drive/MyDrive/Transformer_practice


In [4]:
try:
  from transformers import pipeline
except Exception as e:
  print(e)
  print("installing...")
  !pip install datasets transformers[sentencepiece] -q
  from transformers import pipeline

No module named 'transformers'
installing...
     |████████████████████████████████| 346 kB 5.4 MB/s 
     |████████████████████████████████| 4.2 MB 64.9 MB/s 
     |████████████████████████████████| 86 kB 5.6 MB/s 
     |████████████████████████████████| 86 kB 4.7 MB/s 
     |████████████████████████████████| 140 kB 66.1 MB/s 
     |████████████████████████████████| 212 kB 70.2 MB/s 
     |████████████████████████████████| 1.1 MB 58.0 MB/s 
     |████████████████████████████████| 596 kB 63.6 MB/s 
     |████████████████████████████████| 127 kB 38.9 MB/s 
     |████████████████████████████████| 271 kB 48.4 MB/s 
     |████████████████████████████████| 94 kB 3.1 MB/s 
     |████████████████████████████████| 144 kB 72.2 MB/s 
     |████████████████████████████████| 112 kB 59.2 MB/s 
     |████████████████████████████████| 6.6 MB 43.3 MB/s 
     |████████████████████████████████| 1.2 MB 45.4 MB/s 
ERROR: pip's dependency resolver does not currently take into account all the packages that 

In [5]:
model_name = "bert-base-cased"   ## it is a pretrained model on English language with masked language modeling available on huggingface

In [6]:
## Let's import some tokenizer libraries
from transformers import BertTokenizer, AutoTokenizer

In [7]:
tokenizer = BertTokenizer.from_pretrained(model_name)
auto_tokenizer = AutoTokenizer.from_pretrained(model_name)   

Downloading:   0%|          | 0.00/208k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/426k [00:00<?, ?B/s]

In [8]:
## Let's tokenize one example
example = "This notebook is to show how tokenization happens in transformers"

In [9]:
tokenizer(example)

{'input_ids': [101, 1188, 17189, 1110, 1106, 1437, 1293, 22559, 2734, 5940, 1107, 11303, 1468, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [10]:
auto_tokenizer(example)

{'input_ids': [101, 1188, 17189, 1110, 1106, 1437, 1293, 22559, 2734, 5940, 1107, 11303, 1468, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [11]:
## we can save the tokenizer as well
tokenizer.save_pretrained("./sample_tokenizer")

('./sample_tokenizer/tokenizer_config.json',
 './sample_tokenizer/special_tokens_map.json',
 './sample_tokenizer/vocab.txt',
 './sample_tokenizer/added_tokens.json')

In [12]:
## Let's load the saved tokenizer
loaded_tokenizer = AutoTokenizer.from_pretrained('./sample_tokenizer')


In [13]:
loaded_tokenizer(example)   ## It will give the same output as the above one,

{'input_ids': [101, 1188, 17189, 1110, 1106, 1437, 1293, 22559, 2734, 5940, 1107, 11303, 1468, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [14]:
auto_tokenizer.tokenize(example)   ## This is how words are seggeregated

['This',
 'notebook',
 'is',
 'to',
 'show',
 'how',
 'token',
 '##ization',
 'happens',
 'in',
 'transform',
 '##ers']

In [15]:
## using tokenizer
tokens = tokenizer.tokenize(example)
tokens

['This',
 'notebook',
 'is',
 'to',
 'show',
 'how',
 'token',
 '##ization',
 'happens',
 'in',
 'transform',
 '##ers']

In [16]:
## Converting the tokens into ids
ids = tokenizer.convert_tokens_to_ids(tokens)
ids

## This is the output of the same ids what we saw in the starting just sos and eos are not present here.

[1188, 17189, 1110, 1106, 1437, 1293, 22559, 2734, 5940, 1107, 11303, 1468]

In [17]:
## converting ids to tokens
tokenizer.convert_ids_to_tokens(ids)
## we got the same output

['This',
 'notebook',
 'is',
 'to',
 'show',
 'how',
 'token',
 '##ization',
 'happens',
 'in',
 'transform',
 '##ers']

In [18]:
## Let's use updated ids with sos and eos tokens
updated_ids = [101, 1188, 17189, 1110, 1106, 1437, 1293, 22559, 2734, 5940, 1107, 11303, 1468, 102]
tokenizer.convert_ids_to_tokens(updated_ids)
## Here CLS and SEP are denoted as SOS and EOS

['[CLS]',
 'This',
 'notebook',
 'is',
 'to',
 'show',
 'how',
 'token',
 '##ization',
 'happens',
 'in',
 'transform',
 '##ers',
 '[SEP]']

In [19]:
tokenizer.decode(updated_ids)

'[CLS] This notebook is to show how tokenization happens in transformers [SEP]'

In [20]:
tokenizer.decode(ids)

'This notebook is to show how tokenization happens in transformers'

### Handling multiple sequences

In [21]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [22]:
ckpt = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(ckpt)   ## This will take the tokenizer from ckpt(model)
model = AutoModelForSequenceClassification.from_pretrained(ckpt)

Downloading:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/629 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/255M [00:00<?, ?B/s]

In [23]:
example = "I'm learning Transformers so that I can understand Natural Lnaguage Processing in detail"

In [25]:
tokens = tokenizer.tokenize(example)

In [58]:
ids = tokenizer.convert_tokens_to_ids(tokens)
ids

[1045,
 1005,
 1049,
 4083,
 19081,
 2061,
 2008,
 1045,
 2064,
 3305,
 3019,
 1048,
 2532,
 19696,
 3351,
 6364,
 1999,
 6987]

In [57]:
## Now we need to convert the ids into tensors so that it can be used with the models
ids = torch.tensor(ids)
ids

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


tensor([[ 1045,  1005,  1049,  4083, 19081,  2061,  2008,  1045,  2064,  3305,
          3019,  1048,  2532, 19696,  3351,  6364,  1999,  6987]])

In [59]:
try:
  model(ids)
except Exception as e:
  print(f"Exception occured--->{e}")
  print(e)

Exception occured--->'list' object has no attribute 'size'
'list' object has no attribute 'size'


In [29]:
##  We got the above error because, inorder to provide the ids to model, we need to increase the dimensions, we can achieve it using unsqueeze operation
ids = torch.unsqueeze(ids, dim=0)
ids

tensor([[ 1045,  1005,  1049,  4083, 19081,  2061,  2008,  1045,  2064,  3305,
          3019,  1048,  2532, 19696,  3351,  6364,  1999,  6987]])

In [41]:
model(ids).logits         ## to check the logits from the model

tensor([[-0.1927,  0.3474]], grad_fn=<AddmmBackward0>)

In [31]:
tokenized_inputs = tokenizer(example, return_tensors='pt')   ## it will return tokenized_iput directly into pytorch tensors
tokenized_inputs

{'input_ids': tensor([[  101,  1045,  1005,  1049,  4083, 19081,  2061,  2008,  1045,  2064,
          3305,  3019,  1048,  2532, 19696,  3351,  6364,  1999,  6987,   102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [32]:
tokenized_inputs['input_ids']  ## tokenized_inputs is a dict so we can use it in this way

tensor([[  101,  1045,  1005,  1049,  4083, 19081,  2061,  2008,  1045,  2064,
          3305,  3019,  1048,  2532, 19696,  3351,  6364,  1999,  6987,   102]])

In [33]:
model(tokenized_inputs["input_ids"])   ## In this way we don't have to convert the tokens into tensors explicitly

SequenceClassifierOutput([('logits',
                           tensor([[-1.5181,  1.4738]], grad_fn=<AddmmBackward0>))])

In [34]:
## Whenever we have sentences of variable length needed to be trained we use padding against the shorter sentence, which tells the model that it is non useful data. Every tokenizer has their unique ids to denote padding. Let's see what this tokenizer has to denote
tokenizer.pad_token_id

0

In [35]:
## It uses zero, let's append 0 to our sentence Ids and check once
modified_ids = [1045,
 1005,
 1049,
 4083,
 19081,
 2061,
 2008,
 1045,
 2064,
 3305,
 3019,
 1048,
 2532,
 19696,
 3351,
 6364,
 1999,
 6987,
 0,
 0]

In [36]:
tokenizer.decode(modified_ids)

"i'm learning transformers so that i can understand natural lnaguage processing in detail [PAD] [PAD]"

In [37]:
example_1 = "I've been exploring Transformers for Natural Language Processing."
example_2 = "I've been exploring Transformers."

In [38]:
token_1 = tokenizer.tokenize(example_1)
token_2 = tokenizer.tokenize(example_2)
print(token_1)
print(token_2)

['i', "'", 've', 'been', 'exploring', 'transformers', 'for', 'natural', 'language', 'processing', '.']
['i', "'", 've', 'been', 'exploring', 'transformers', '.']


In [39]:
id_1 = tokenizer.convert_tokens_to_ids(token_1)
id_2 = tokenizer.convert_tokens_to_ids(token_2)
print(id_1)
print(id_2)

[1045, 1005, 2310, 2042, 11131, 19081, 2005, 3019, 2653, 6364, 1012]
[1045, 1005, 2310, 2042, 11131, 19081, 1012]


In [43]:
## Now let's try to feed the ids into the model and check the logits
batch_ids=[
           id_1,id_2
]
try:
  model(torch.tensor(batch_ids)).logits
except Exception as e:
  print(f"Exception occured---> {e}")

Exception occured---> expected sequence of length 11 at dim 1 (got 7)


### The above exception shows that the second sentence fed to the model only has 7 words while the first had the 11 words. So we understood here the importance of padding and now we need to pad the second sentence

In [45]:
## Now let's try to add padding sequence to second sentence
max_len = 11

while len(id_2)!= max_len:
  id_2.append(tokenizer.pad_token_id)
id_2

[1045, 1005, 2310, 2042, 11131, 19081, 1012, 0, 0, 0, 0]

In [46]:
## Now we can see that 4 padding 0s are added to second sentence, let's check the sentence once
tokenizer.decode(id_2)

"i've been exploring transformers. [PAD] [PAD] [PAD] [PAD]"

In [47]:
batch_same_sequence_len=[id_1,id_2]

In [48]:
model(torch.tensor(batch_same_sequence_len)).logits

tensor([[ 0.9019, -0.6752],
        [ 0.7740, -0.6163]], grad_fn=<AddmmBackward0>)

## Now its working fine
# Logits--> Logits are the layer output just before the softmax one.

In [49]:
## Not only this, now we need to add the attention mask as well, so attention mask for padding will be 0 and other things 1.
attention_mask = [
                  [1]*11,    ## because we want attention on all the words
                  [1]*7 + [0]*4   ## because we only want attention on words and not on padding
]
attention_mask

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]]

In [51]:
## Now we can feed the attention block to the model as well
model(
    torch.tensor(batch_same_sequence_len),
    attention_mask = torch.tensor(attention_mask)
).logits

tensor([[ 0.9019, -0.6752],
        [-0.5456,  0.7677]], grad_fn=<AddmmBackward0>)

#### We can see that the logits are different after appliying attention_mask.

## There are some other methods as well rather than padding and that is truncation.

## So our model will be configured to deal with certain length of sequence sentences only, for eg 512 or 1024 etc. Now if some sentences of more than 512 or 1024 comes then we will truncate the remaining lenght of sentences apart from 512 or 1024. Yes in that case there are chances of losing valuable information as well.

# Remember, these are just some concepts of transformers which we are practicing, there are better methods available to do all these either automatically or with better manual approaches.